### ISSUE TITLE
CWR error:  error: flag provided but not defined: -e

### ISSUE THREAD

**Issue by arosales** [juju-solutions/cloud-weather-report#16]
I was trying to get a CWR to run against the realtime-syslog-analytics bundle via:

    $ cwr -v -b bundle.yaml aws-west2 ./realtime-syslog-analytics.yaml 
 
In doing so I hit the following error:

```
2016-04-26 13:57:55 ERROR Command (juju bootstrap -e aws-west2) Output:

 error: flag provided but not defined: -e

2016-04-26 13:57:55 DEBUG Updating JUJU_ENV: "aws-west2" -> ""
Traceback (most recent call last):
  File "/usr/local/bin/cwr", line 9, in <module>
    load_entry_point('cloud-weather-report==0.2.1', 'console_scripts', 'cwr')()
  File "/usr/local/lib/python2.7/dist-packages/cloudweatherreport/run.py", line 21, in entry
    html_filename = main(args)
  File "/usr/local/lib/python2.7/dist-packages/cloudweatherreport/cloud_weather_report.py", line 145, in main
    args=args, env=env_name, test_plan=test_plan)
  File "/usr/local/lib/python2.7/dist-packages/cloudweatherreport/cloud_weather_report.py", line 77, in run_bundle_test
    status = tester.main(args)
  File "/usr/local/lib/python2.7/dist-packages/bundletester/tester.py", line 120, in main
    [report.emit(result) for result in run()]
  File "/usr/local/lib/python2.7/dist-packages/bundletester/runner.py", line 133, in __call__
    bootstrapped = self.builder.bootstrap()
  File "/usr/local/lib/python2.7/dist-packages/bundletester/builder.py", line 36, in bootstrap
    self.environment.bootstrap()
  File "/usr/lib/python2.7/dist-packages/deployer/env/base.py", line 74, in bootstrap
    params, self.log, "Failed to bootstrap")
  File "/usr/lib/python2.7/dist-packages/deployer/env/base.py", line 21, in _check_call
    return _check_call(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/deployer/utils.py", line 272, in _check_call
    raise ErrorExit(e)
deployer.utils.ErrorExit
```

more details at:
http://paste.ubuntu.com/16071717/

**Comment by marcoceppi** [comment]
This is likely due to the switch-er-oo between juju-1 and juju (and no longer supporting update-alternatives). We'll need to do a better job anticipating juju version from the user and dispatching accordingly

**Comment by seman** [comment]
This is due to using Juju-2 instead of juju-1 to run the cwr.
