### ISSUE TITLE
Ambigious bundle options error even thought I specify the bundle in the test plan

### ISSUE THREAD

**Issue by arosales** [juju-solutions/cloud-weather-report#17]
I have the following test plan which specifies bundle.yaml:
```
$ cat realtime-syslog-analytics.yaml 
bundle: bundle:realtime-syslog-analytics
benchmark:
    plugin:
        terasort
bundle_name: realtime-syslog-analytics
bundle_file: bundle.yaml

However, CWR gives me the following error on Ambiguous bundle given the realtime-syslog-analytics bundle has multiple bundle.yaml files:

$ cwr -v aws-west2 ./realtime-syslog-analytics.yaml 
2016-04-26 13:50:16 INFO Cloud Weather Report started.
2016-04-26 13:50:16 INFO Running test on AWS.
2016-04-26 13:50:16 DEBUG Downloading https://api.jujucharms.com/charmstore/v4/realtime-syslog-analytics/archive
2016-04-26 13:50:16 INFO Starting new HTTPS connection (1): api.jujucharms.com
2016-04-26 13:50:17 DEBUG "GET /charmstore/v4/realtime-syslog-analytics/archive HTTP/1.1" 200 6017
2016-04-26 13:50:17 DEBUG Extracting /tmp/bundletester-RsnBiN/tmp1n91tC to /tmp/bundletester-RsnBiN/tmpJPWoNa
2016-04-26 13:50:17 DEBUG unzip /tmp/bundletester-RsnBiN/tmp1n91tC -d /tmp/bundletester-RsnBiN/tmpJPWoNa: Archive:  /tmp/bundletester-RsnBiN/tmp1n91tC
  inflating: /tmp/bundletester-RsnBiN/tmpJPWoNa/README.md  
  inflating: /tmp/bundletester-RsnBiN/tmpJPWoNa/bundle-dev.yaml  
  inflating: /tmp/bundletester-RsnBiN/tmpJPWoNa/bundle-local.yaml  
  inflating: /tmp/bundletester-RsnBiN/tmpJPWoNa/bundle.yaml  
   creating: /tmp/bundletester-RsnBiN/tmpJPWoNa/tests/
  inflating: /tmp/bundletester-RsnBiN/tmpJPWoNa/tests/01-bundle.py  
  inflating: /tmp/bundletester-RsnBiN/tmpJPWoNa/tests/tests.yaml  

Traceback (most recent call last):
  File "/usr/local/bin/cwr", line 9, in <module>
    load_entry_point('cloud-weather-report==0.2.1', 'console_scripts', 'cwr')()
  File "/usr/local/lib/python2.7/dist-packages/cloudweatherreport/run.py", line 21, in entry
    html_filename = main(args)
  File "/usr/local/lib/python2.7/dist-packages/cloudweatherreport/cloud_weather_report.py", line 145, in main
    args=args, env=env_name, test_plan=test_plan)
  File "/usr/local/lib/python2.7/dist-packages/cloudweatherreport/cloud_weather_report.py", line 77, in run_bundle_test
    status = tester.main(args)
  File "/usr/local/lib/python2.7/dist-packages/bundletester/tester.py", line 108, in main
    suite = spec.SuiteFactory(options, options.testdir)
  File "/usr/local/lib/python2.7/dist-packages/bundletester/spec.py", line 262, in SuiteFactory
    model = classifier(directory, options)
  File "/usr/local/lib/python2.7/dist-packages/bundletester/spec.py", line 216, in BundleClassifier
    bundle = find_bundle_file(directory, options.bundle)
  File "/usr/local/lib/python2.7/dist-packages/bundletester/spec.py", line 211, in find_bundle_file
    "Ambigious bundle options: %s. Disambiguate with --bundle" % yamls)
OSError: Ambigious bundle options: ['/tmp/bundletester-RsnBiN/tmpJPWoNa/bundle-local.yaml', '/tmp/bundletester-RsnBiN/tmpJPWoNa/bundle.yaml', '/tmp/bundletester-RsnBiN/tmpJPWoNa/bundle-dev.yaml']. Disambiguate with --bundle
```

I expected CWR to use "bundle.yaml" since that was in the the test plan. I was able to work around this issue by specifying the "-b" option:

`arosales@x230:~/devel/cloud-weather-report/build-cloud/test_plans$ cwr -v -b bundle.yaml aws-west2 ./realtime-syslog-analytics.yaml `

These seemed to get me around the Ambigious error

**Comment by seman** [comment]
If there are multiple bundle files, Bundletester expects you to use "-b" to disambiguate. This is also displayed on error message "Ambiguous bundle options ... Disambiguate with --bundle"

**Comment by arosales** [comment]
> If there are multiple bundle files, Bundletester expects you to use "-b" to disambiguate. This is also displayed on error message "Ambiguous bundle options ... Disambiguate with --bundle"

Agreed, however I thought the "bundle" key in the test plan specified which bundle to use specifically when there is more than one bundle as in this case.

For this test plan we have:

```
$ cat realtime-syslog-analytics.yaml 
bundle: bundle:realtime-syslog-analytics
benchmark:
    plugin:
        terasort
bundle_name: realtime-syslog-analytics
bundle_file: bundle.yaml
```

Note:
`bundle_file: bundle.yaml
`

I was under the impression this would specify the bundle to use in the test, however I still get an ambiguous error. Thus, this bug was to clearify that point.

-thanks,
Antonio

**Comment by seman** [comment]
Resolved by https://github.com/juju-solutions/cloud-weather-report/pull/41
