### ISSUE TITLE
Amulet dependency unable to be installed

### ISSUE THREAD

**Issue by arosales** [juju-solutions/cloud-weather-report#32]
I installed CWR on a fresh Xenial cloud instance and got the following error:

```
ubuntu@juju-1:~/devel/cwr$ cwr -v -F -b bundle.yaml aws-east1 build-cloud/test_plans/bigtop-processing-mapreduce.yaml
2016-05-08 23:28:32 INFO Cloud Weather Report started.
2016-05-08 23:28:33 INFO Running test on AWS.
2016-05-08 23:28:33 DEBUG Downloading https://api.jujucharms.com/charmstore/v4/~bigdata-dev/bigtop-processing-mapreduce/archive
2016-05-08 23:28:33 INFO Starting new HTTPS connection (1): api.jujucharms.com
2016-05-08 23:28:34 DEBUG "GET /charmstore/v4/~bigdata-dev/bigtop-processing-mapreduce/archive HTTP/1.1" 200 9894
2016-05-08 23:28:34 DEBUG Extracting /tmp/bundletester-BDIIUf/tmpiKQyo0 to /tmp/bundletester-BDIIUf/tmp27eUlp
2016-05-08 23:28:34 DEBUG unzip /tmp/bundletester-BDIIUf/tmpiKQyo0 -d /tmp/bundletester-BDIIUf/tmp27eUlp: Archive:  /tmp/bundletester-BDIIUf/tmpiKQyo0
  inflating: /tmp/bundletester-BDIIUf/tmp27eUlp/LICENSE  
  inflating: /tmp/bundletester-BDIIUf/tmp27eUlp/README.md  
  inflating: /tmp/bundletester-BDIIUf/tmp27eUlp/bundle-dev.yaml  
  inflating: /tmp/bundletester-BDIIUf/tmp27eUlp/bundle-local.yaml  
  inflating: /tmp/bundletester-BDIIUf/tmp27eUlp/bundle.yaml  
  inflating: /tmp/bundletester-BDIIUf/tmp27eUlp/copyright  
   creating: /tmp/bundletester-BDIIUf/tmp27eUlp/tests/
  inflating: /tmp/bundletester-BDIIUf/tmp27eUlp/tests/01-bundle.py  
  inflating: /tmp/bundletester-BDIIUf/tmp27eUlp/tests/tests.yaml  

2016-05-08 23:28:34 DEBUG Cache dir /home/ubuntu/.juju/.deployer-store-cache/cs_trusty_ganglia-node-2
2016-05-08 23:28:34 DEBUG Cache dir /home/ubuntu/.juju/.deployer-store-cache/cs_trusty_hadoop-client-3
2016-05-08 23:28:34 DEBUG Cache dir /home/ubuntu/.juju/.deployer-store-cache/cs_~bigdata-dev_trusty_apache-bigtop-slave-9
2016-05-08 23:28:34 DEBUG Cache dir /home/ubuntu/.juju/.deployer-store-cache/cs_~bigdata-dev_trusty_apache-bigtop-resourcemanager-10
2016-05-08 23:28:34 DEBUG Cache dir /home/ubuntu/.juju/.deployer-store-cache/cs_~bigdata-dev_trusty_apache-bigtop-plugin-7
2016-05-08 23:28:34 DEBUG Cache dir /home/ubuntu/.juju/.deployer-store-cache/cs_~bigdata-dev_trusty_apache-bigtop-namenode-11
2016-05-08 23:28:34 DEBUG Cache dir /home/ubuntu/.juju/.deployer-store-cache/cs_trusty_ganglia-2
2016-05-08 23:28:34 DEBUG Updating JUJU_ENV: "" -> "aws-east1"
E: Unable to locate package amulet
2016-05-08 23:28:34 DEBUG Updating JUJU_ENV: "aws-east1" -> ""
2016-05-08 23:28:34 ERROR Test failed in aws-east1 Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cloudweatherreport/cloud_weather_report.py", line 86, in run_bundle_test
    status = tester.main(args)
  File "/usr/local/lib/python2.7/dist-packages/bundletester/tester.py", line 141, in main
    [report.emit(result) for result in run()]
  File "/usr/local/lib/python2.7/dist-packages/bundletester/runner.py", line 133, in __call__
    self.build()
  File "/usr/local/lib/python2.7/dist-packages/bundletester/runner.py", line 123, in build
    self.builder.install_packages()
  File "/usr/local/lib/python2.7/dist-packages/bundletester/builder.py", line 165, in install_packages
    subprocess.check_call(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['sudo', 'apt-get', 'install', '-qq', '-y', 'amulet', 'python3-yaml']' returned non-zero exit status 100

Test result:
  results/bundle__bigdata_dev_bigtop_processing_mapreduce-2016-05-08T23:28:32-result.html
ubuntu@juju-1:~/devel/cwr$

```

python3-yaml is installed, but it looks like it is having issues with amulet.

```
ubuntu@juju-1:~/devel/cwr$ apt search amulet
Sorting... Done
Full Text Search... Done
nethack-common/xenial 3.4.3-15build1 amd64
  dungeon crawl game - common files

nethack-console/xenial 3.4.3-15build1 amd64
  dungeon crawl game - text-based interface

nethack-el/xenial 1:0.9.5-3 all
  Emacs major-mode for playing NetHack

nethack-lisp/xenial 3.4.3-15build1 amd64
  dungeon crawl game - Lisp interface

nethack-x11/xenial 3.4.3-15build1 amd64
  dungeon crawl game - X11 interface

slashem/xenial 0.0.7E7F3-7build1 amd64
  variant of Nethack

slashem-gtk/xenial 0.0.7E7F3-7build1 amd64
  variant of Nethack (Gtk window port)

slashem-sdl/xenial 0.0.7E7F3-7build1 amd64
  variant of Nethack (SDL window port)

slashem-x11/xenial 0.0.7E7F3-7build1 amd64
  variant of Nethack (X11 window port)

ubuntu@juju-1:~/devel/cwr$ 
```

On Xenial do we need to enable the Juju Stable ppa to get access to the amulet dependency?

-thanks,
Antonio

**Comment by tvansteenburgh** [comment]
That may be the case on Xenial right now. This can/should be solved in the bundle itself by adding an entry to the `tests/tests.yaml` file:

```yaml
sources:
  - ppa:juju/stable
```

**Comment by seman** [comment]
As mentioned above, add the source ppa in the bundle. No change requires in CWR.
