### ISSUE TITLE
CWR 0.3.9 breaks juju 1.x on ubuntu 14.04 compatibility

### ISSUE THREAD

**Issue by galgalesh** [juju-solutions/cloud-weather-report#60]
Cloud weather report 0.3.9 on Ubuntu 14.04 speaking to a Juju 1 environment:

```
Traceback (most recent call last):
  File "/usr/local/bin/cwr", line 9, in <module>
    load_entry_point('cloud-weather-report==0.3.9', 'console_scripts', 'cwr')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/cloudweatherreport/run.py", line 6, in <module>
    from cloud_weather_report import (
  File "/usr/local/lib/python2.7/dist-packages/cloudweatherreport/cloud_weather_report.py", line 16, in <module>
    from reporter import Reporter
  File "/usr/local/lib/python2.7/dist-packages/cloudweatherreport/reporter.py", line 14, in <module>
    from utils import (
  File "/usr/local/lib/python2.7/dist-packages/cloudweatherreport/utils.py", line 20, in <module>
    from jujuclient.juju1.environment import Environment as env1
ImportError: No module named juju1.environment
```

**Comment by seman** [comment]
Please update your jujuclient and juju-deployer packages to the latest.

**Comment by galgalesh** [comment]
This is happening in lxc containers that are recreated and reinstalled
before every test run so they should be the latest version... These
containers have been reinstalled multiple times throughout the day with the
same result...

2016-08-08 19:20 GMT+02:00 seman <notifications@github.com>:

**Comment by tvansteenburgh** [comment]
The problem is the "latest" packages are only available in ppa:tvansteenburgh/ppa right now.

**Comment by galgalesh** [comment]
Using your ppa seems to work. I guess I'll use that as a workaround until the packages are added to trusty. Is it possible to notify me when that happens?

**Comment by tvansteenburgh** [comment]
@galgalesh Sure, I'll make an announcement on the Juju mailing list.

**Comment by seman** [comment]
With the current releases, we are targeting to support Juju 2.0
