### ISSUE TITLE
CWR errors out with version mismatch for packages

### ISSUE THREAD

**Issue by secroft** [juju-solutions/cloud-weather-report#67]
Juju 2.0 rc3
MAAS 2.1 beta3
Ubuntu LTS 16.04.1

ubuntu@OrangeBox04:~/cwr$ cwr maas sa-test.yaml
Traceback (most recent call last):
  File "/usr/local/bin/cwr", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 2991, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2977, in _call_aside
    f(_args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3004, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 664, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 677, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 861, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (PyYAML 3.12 (/usr/local/lib/python2.7/dist-packages), Requirement.parse('PyYAML==3.11'), set(['jujubundlelib']))

**Comment by seman** [comment]
Could uninstall and reinstall PyYAML==3.11 instead of 3.12 . Not sure why `jujubundlelib` pinned to 3.11.

**Comment by seman** [comment]
This issue is tracked here https://github.com/juju/juju-bundlelib/issues/55
